
#- hosts: target2
#  become: yes
#  tasks:
          - name: Mount the FS of LVM
            mount:
                    fstype: ext4
                    src: /dev/vg1/lv1
                    path: /tar/mount
                    state: mounted
